/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_architecture_blueprints_todoapp_jni_WeatherJNI */

#ifndef _Included_com_example_android_architecture_blueprints_todoapp_jni_WeatherJNI
#define _Included_com_example_android_architecture_blueprints_todoapp_jni_WeatherJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_architecture_blueprints_todoapp_jni_WeatherJNI
 * Method:    weatherKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_android_architecture_blueprints_todoapp_jni_WeatherJNI_weatherKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
